### ISSUE TITLE
Use config gem instead of hardcoding ENV variables

### ISSUE THREAD

**Issue by kigster** [ello/kinesis-stream-reader#20]
hey, would you guys be open to using something like [RailsConfig](https://github.com/railsconfig/config) gem for providing configuration to this library, instead of hard-coding environment variables?

With the RailsConfig gem, you could still use your environment variables without any changes. At the same time, it will allow others, who may prefer `YAML` or other types of configuration to easily configure your gem with a config file.

If you are open to this, I'll update the gem and submit a PR, but I don't want to bother if there are fundamental reasons that you are opposed to a file based configuration.

I am contemplating on leveraging your library in a webhooks application, that adapts a Kinesis event stream into a series of asynchronous HTTP webhooks.

Thanks!

**Comment by jayzes** [comment]
Hey there - thanks for the note! We wouldn't want to tie it to anything that requires Rails (some of our consumers are pure Ruby and don't have that dependency) but something that moves the configuration out to a `config` block that you could populate any way you want instead of just grabbing the ENV vars would suit both use cases, I think.

**Comment by kigster** [comment]
@jayzes Jay, thanks for your response! 

I know, RailsConfig is a horribly confusing name :) The gem is actually just called `config`, and does not depend on Rails, although it does include `activesupport` for something stupid, I am sure :) 

Would that be acceptable?
